name: simple_shared_preferences_example
description: Demonstrates hot to use the preferences.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  simple_shared_preferences:
    path: ../


dev_dependencies:
  camus_lints: ^1.1.1
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
